import './globals.css';
import { Inter, Noto_Sans } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });
const notoSans = Noto_Sans({ weight: '400', subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={notoSans.className}>{children}</body>
    </html>
  );
}
